name: Deploy to GitHub Pages

# on:
#   push:
#     branches: ["master"]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Build website
        run: yarn build

      - uses: hujiulong/action-qiniu-upload@master
        with:
          access_key: ${{ secrets.QINIU_ACCESS_KEY }}
          secret_key: ${{ secrets.QINIU_SECRET_KEY }}
          bucket: ${{ secrets.QINIU_BUCKET_SITE }}
          source_dir: "./build"
          dest_dir: "/"
          ignore_source_map: true

  notification:
    runs-on: ubuntu-latest
    needs: deploy
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@v2

      - uses: benjlevesque/short-sha@v2.1
        id: short-sha
        with: { length: 7 }

      - name: 🎯 Telegram Notification
        if: env.WORKFLOW_CONCLUSION == 'success'
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.CHANNEL_CHAT_ID }}
          token: ${{ secrets.BOT_TOKEN }}
          format: markdown
          message: |
            🎉 [Site](https://github.com/SIT-kite/site)  Build  *${{ env.WORKFLOW_CONCLUSION }}*
            Author: *${{ github.actor }}*
            Message: *${{ github.event.head_commit.message }}*
            Commit: [${{ env.SHA }}](https://github.com/${{ github.repository }}/commit/${{ env.SHA }})

      - name: 🎯 Telegram Notification
        if: env.WORKFLOW_CONCLUSION != 'success'
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.CHANNEL_CHAT_ID }}
          token: ${{ secrets.BOT_TOKEN }}
          format: markdown
          message: |
            🔴 [Site](https://github.com/SIT-kite/site)  Build  *${{ env.WORKFLOW_CONCLUSION }}*
            Author: *${{ github.actor }}*
            Message: *${{ github.event.head_commit.message }}*
            Commit: [${{ env.SHA }}](https://github.com/${{ github.repository }}/commit/${{ env.SHA }})
